# Generated by Django 2.0.13 on 2019-08-15 13:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallEndRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('START', 'start'), ('END', 'end')], default='END', max_length=3, verbose_name='TYPE')),
                ('timestamp', models.DateTimeField(verbose_name='TIMESTAMP')),
                ('call_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'call_end_record',
                'verbose_name_plural': 'call_end_records',
                'db_table': 'CallEndRecord',
            },
        ),
        migrations.CreateModel(
            name='CallStartRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(verbose_name='TIMESTAMP')),
                ('call_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('START', 'start'), ('END', 'end')], default='START', max_length=4, verbose_name='TYPE')),
                ('source', models.CharField(max_length=11, verbose_name='SOURCE')),
                ('destination', models.CharField(max_length=11, verbose_name='DESTINATION')),
            ],
            options={
                'verbose_name': 'call_start_record',
                'verbose_name_plural': 'call_start_records',
                'db_table': 'CallStartRecord',
            },
        ),
    ]
