# Generated by Django 2.0.13 on 2019-08-15 19:55

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallEndRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(verbose_name='TIMESTAMP')),
                ('call_id', models.UUIDField(unique=True, verbose_name='CALL_ID')),
            ],
            options={
                'verbose_name': 'call_end_record',
                'verbose_name_plural': 'call_end_records',
                'db_table': 'CallEndRecord',
            },
        ),
        migrations.CreateModel(
            name='CallStartRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(verbose_name='TIMESTAMP')),
                ('call_id', models.UUIDField(unique=True, verbose_name='CALL_ID')),
                ('source', models.CharField(max_length=11, verbose_name='SOURCE')),
                ('destination', models.CharField(max_length=11, verbose_name='DESTINATION')),
            ],
            options={
                'verbose_name': 'call_start_record',
                'verbose_name_plural': 'call_start_records',
                'db_table': 'CallStartRecord',
            },
        ),
        migrations.CreateModel(
            name='TelephoneBill',
            fields=[
                ('call_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('destination', models.CharField(max_length=11, verbose_name='DESTINATION')),
                ('call_start_date', models.DateTimeField(verbose_name='CALL_START_DATE')),
                ('call_start_time', models.TimeField(verbose_name='CALL_START_TIME')),
                ('call_duration', models.TimeField(verbose_name='CALL_DURATION')),
                ('call_price', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=17)),
                ('source', models.CharField(max_length=11, verbose_name='SOURCE')),
            ],
            options={
                'verbose_name': 'telephone_bill',
                'verbose_name_plural': 'telephone_bills',
                'db_table': 'TelephoneBill',
            },
        ),
    ]
