# Generated by Django 2.0.13 on 2019-08-15 18:13

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('work_at_olist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelephoneBill',
            fields=[
                ('call_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('destination', models.CharField(max_length=11, verbose_name='DESTINATION')),
                ('call_start_date', models.DateTimeField(verbose_name='CALL_START_DATE')),
                ('call_start_time', models.TimeField(verbose_name='CALL_START_TIME')),
                ('call_duration', models.TimeField(verbose_name='CALL_DURATION')),
                ('call_price', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=17)),
                ('source', models.CharField(max_length=11, verbose_name='SOURCE')),
            ],
            options={
                'verbose_name': 'telephone_bill',
                'verbose_name_plural': 'telephone_bills',
                'db_table': 'TelephoneBill',
            },
        ),
    ]
