# Generated by Django 2.0.13 on 2019-08-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_at_olist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephonebill',
            name='call_start_time',
            field=models.CharField(max_length=8, verbose_name='CALL_START_TIME'),
        ),
    ]
