# Generated by Django 2.0.13 on 2019-08-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_at_olist', '0002_auto_20190816_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephonebill',
            name='call_duration',
            field=models.CharField(max_length=32, verbose_name='CALL_DURATION'),
        ),
    ]
