# Generated by Django 2.0.13 on 2019-08-16 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_at_olist', '0003_auto_20190816_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telephonebill',
            old_name='call_start_date',
            new_name='call_start_timestamp',
        ),
    ]
